<?php include('layout/header.phtml'); ?>

    <!-- Start Top Bar -->
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">
            <a href="<?= $baseUrl ?>"> Multi level categories</a>
          </li>
        <?= $categories; ?>
        <!--  <li class="has-submenu">
            <a href="<?= $baseUrl ?>/show-category/1">Electronics</a>
            <ul class="submenu menu vertical" data-submenu>
              <li><a href="<?= $baseUrl?>show-category/2,Monitors">Monitors</a></li>
              <li><a href="#">Tablets</a></li>
              <li>
                <a href="#">Computers</a>
                <ul class="submenu menu vertical" data-submenu>
                  <li><a href="#">Desktops</a></li>
                  <li><a href="#">Notebooks</a></li>
                  <li>
                    <a href="#">Laptops</a>
                    <ul class="submenu menu vertical" data-submenu>
                      <li><a href="#">Asus</a></li>
                      <li><a href="#">Dell</a></li>
                      <li>
                        <a href="#">Acer</a>
                        <ul class="submenu menu vertical" data-submenu>
                          <li><a href="<?= $baseUrl?>show-category/7,FullHD">FullHD</a></li>
                          <li><a href="#">HD+</a></li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
          </li> -->
          <!--<li><a href="#">Videos</a></li>
          <li>
            <a href="#">Software</a>
            <ul class="submenu menu vertical" data-submenu>
              <li>
                <a href="#">Operating systems</a>
                <ul class="submenu menu vertical" data-submenu>
                  <li><a href="#">Linux</a></li>
                </ul>
              </li>
              <li><a href="#">Servers</a></li>
            </ul>
          </li> -->
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search" /></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div>
    <!-- End Top Bar -->
    <br />
    <br />
    <div class="grid-container">
      <div class="grid-x grid-margin-x">
        <div class="medium-6 cell">
          <h3>
            <?php if($editCategory ?? false): ?>
                 Edit category
            <?php else: ?>
                 Add a new category
            <?php endif; ?>

          </h3>
          <?php if(isset($categorySaved)  && $categorySaved == false): ?>
          <div class="callout alert">
            Fill correctly the form
          </div>
          <?php elseif(isset($categorySaved) && $categorySaved == true): ?>
            <?php ?>
            <div class="callout alert">
                Category was saved
            </div>
            <?php endif; ?>
          <?php if($category_deleted ?? false): ?>
          <div class="callout alert">
                      Category was deleted
          </div>
          <?php endif; ?>
          <form method="post" action="<?= $baseUrl ?>save-category">
          <label>Name
            <input name="category_name" type="text" placeholder="Name"
            value="<?= $editCategory ?? null ?>"
            required/>
          </label>
          <label
            >Description
            <textarea name="category_description" placeholder="Description"
           required></textarea>
          </label>
          <label
            >Parent category
            <select>
              <option>--choose--</option>
              <option value="">Electronics</option>
              <option value="">&nbsp;&nbsp;Monitors</option>
              <option value="">&nbsp;&nbsp;Tablets</option>
              <option value="">&nbsp;&nbsp;Computers</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Desktops</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Notebooks</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Laptops</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asus</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dell</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acer</option>
              <option value=""
                >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FullHD</option
              >
              <option value=""
                >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HD+</option
              >
              <option value="">Videos</option>
              <option value="">Software</option>
              <option value="">&nbsp;&nbsp;Operating systems</option>
              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Linux</option>
              <option value="">&nbsp;&nbsp;Servers</option>
            </select>
          </label>
          <input
            type="submit"
            class="button expanded"
            value="Save category"
          />
          </form>
        </div>

        <div class="medium-6 large-5 cell large-offset-1">
          <div class="basic-card">
            <div class="basic-card-content content callout secondary">
              <h5><?= $category ?? 'Choose a category from the menu' ?></h5>
              <?php if($category ?? false): ?>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi
                saepe, asperiores dolor nesciunt dolore, accusamus minus
                repellendus vero odio, quibusdam, ipsum nisi in a molestiae ex
                assumenda nulla eveniet eos!
              </p>
              <?php endif;?>
            </div>
            <?php if($category ?? false): ?>
            <div class="links callout primary">
              <ul class="menu">
                <li>
                  <a href="<?= $baseUrl ?>/edit-category/1">Edit</a>
                </li>
                <li>
                  <a href="<?= $baseUrl?>delete-category/1"
                   id="delete-category-confirmation"
                                        onclick="return confirm('Are you sure')"
                  >Delete</a>
                </li>
              </ul>
            </div>
            <?php  endif;?>
          </div>
        </div>
      </div>

      <hr />
    </div>

<?php include('layout/footer.phtml'); ?>
