<?php include('layout/header.phtml'); ?>

    <!-- Start Top Bar -->
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">
            <a href="<?= $baseUrl ?>"> Multi level categories</a>
          </li>
        <?= $categories; ?>
      
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search" /></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div>
    <!-- End Top Bar -->
    <br />
    <br />
    <div class="grid-container">
      <div class="grid-x grid-margin-x">
        <div class="medium-6 cell">
          <h3>
            <?php if($editCategory ?? false): ?>
                 Edit category
            <?php else: ?>
                 Add a new category
            <?php endif; ?>

          </h3>
          <?php if(isset($categorySaved)  && $categorySaved == false): ?>
          <div class="callout alert">
            Fill correctly the form
          </div>
          <?php elseif(isset($categorySaved) && $categorySaved == true): ?>
            <?php ?>
            <div class="callout alert">
                Category was saved
            </div>
            <?php endif; ?>
          <?php if($category_deleted ?? false): ?>
          <div class="callout alert">
                      Category was deleted
          </div>
          <?php endif; ?>
          <form method="post" action="<?= $baseUrl ?>save-category">
          <label>Name
            <input name="category_name" type="text" placeholder="Name"
            value="<?= $editCategory['name'] ?? null ?>"
            required/>
          </label>
          <label
            >Description
            <textarea name="category_description" placeholder="Description"
           required><?= $editCategory['description'] ?? null ?></textarea>
          </label>
          <label
            >Parent category
            <select id="select_category_list" name="category_parent">
              <option>--choose--</option>
                <?php foreach($select_list_categories as $category_for_select): ?>
                      <?php if(isset($editCategory) && $editCategory->parent_id == $category_for_select['id']): ?>
                        <option selected value="<?=$category_for_select['id']?>"><?=$category_for_select['name']?></option>
                      <?php else: ?>
                     <option value="<?=$category_for_select['id']?>"><?=$category_for_select['name']?></option>
                      <?php endif; ?>
                <?php endforeach; ?>
            </select>
          </label>
          <input
            type="submit"
            class="button expanded"
            value="Save category"
          />
          </form>
        </div>

        <div class="medium-6 large-5 cell large-offset-1">
          <div class="basic-card">
            <div class="basic-card-content content callout secondary">
              <h5><?= $category->name ?? 'Choose a category from the menu' ?></h5>
              <?php if($category->description ?? false): ?>
              <p>
               <?= $category->description?>
              </p>
              <?php endif;?>
            </div>
            <?php if($category ?? false): ?>
            <div class="links callout primary">
              <ul class="menu">
                <li>
                  <a href="<?= $baseUrl ?>/edit-category/<?= $category->id; ?>">Edit</a>
                </li>
                <li>
                  <a href="<?= $baseUrl?>delete-category/<?= $category->id; ?>"
                   id="delete-category-confirmation"
                                        onclick="return confirm('Are you sure')"
                  >Delete</a>
                </li>
              </ul>
            </div>
            <?php  endif;?>
          </div>
        </div>
      </div>

      <hr />
    </div>

<?php include('layout/footer.phtml'); ?>
